### ISSUE TITLE
Spaces in PATH = Couldn't launch python

### ISSUE THREAD

**Issue by bouiboui** [EmpireMediaScience/A1111-Web-UI-Installer#12] opened 2022-12-22 10:32 UTC
![image](https://user-images.githubusercontent.com/3274103/209114479-6c5e32ac-27d8-433d-b1ee-1d9af5d97597.png)

First of all, thanks for this project, it's great 👍 
I've got the issue above. I couldn't pinpoint where the issue is in the code exactly.

**Comment by Mozoloa** [comment] 2022-12-23 01:37
interesting, what does 
`Get-ItemProperty -path "hkcu:\Software\Python\PythonCore\3.10\InstallPath"`
output in powershell ?

**Comment by bouiboui** [comment] 2022-12-23 08:07
```sh
PS C:\Users\Julien> Get-ItemProperty -path "hkcu:\Software\Python\PythonCore\3.10\InstallPath"


(default)              : C:\Program
                         Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0
ExecutablePath         : C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8
                         p0\python3.10.exe
WindowedExecutablePath : C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8
                         p0\pythonw3.10.exe
PSPath                 : Microsoft.PowerShell.Core\Registry::HKEY_CURRENT_USER\Software\Python\PythonCore\3.10\InstallP
                         ath
PSParentPath           : Microsoft.PowerShell.Core\Registry::HKEY_CURRENT_USER\Software\Python\PythonCore\3.10
PSChildName            : InstallPath
PSDrive                : HKCU
PSProvider             : Microsoft.PowerShell.Core\Registry
```

**Comment by Mozoloa** [comment] 2022-12-24 00:10
Interesting, here's what it's doing
https://github.com/EmpireMediaScience/A1111-Web-UI-Installer/blob/88badbc07f4a1f05c3a9c60d42304abeb492af59/Launcher/Functions.psm1#L171-L181

It's then piping the ExecutablePath in env:PYTHON in the WebUI, which might be where the problem lies.

Can you do the following
Launch via webui-user.bat, if it works then it's odd, else:
Add to webui-user.bat:  `"C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\python3.10.exe"` after `PYTHON=`

Launch via webui-user.bat, and see if you still get the error, if so then the error is unrelated to my launcher

**Comment by walkerakiz** [comment] 2022-12-24 01:12
Have the same issue! If launch it from the launchUI.bat works charm. Any fix?

**Comment by walkerakiz** [comment] 2022-12-24 01:19
> Interesting, here's what it's doing
> 
> https://github.com/EmpireMediaScience/A1111-Web-UI-Installer/blob/88badbc07f4a1f05c3a9c60d42304abeb492af59/Launcher/Functions.psm1#L171-L181
> 
> It's then piping the ExecutablePath in env:PYTHON in the WebUI, which might be where the problem lies.
> 
> Can you do the following
> 
> 1. Launch via webui-user.bat, if it works then it's odd, else:
> 2. Add to webui-user.bat:  `"C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\python3.10.exe"` after `PYTHON=`
> 3. Launch via webui-user.bat, and see if you still get the error, if so then the error is unrelated to my launcher

I did edit aswell the webui-user.bat and added after the PYTHON= my path, still working but the launcher wont work.

**Comment by walkerakiz** [comment] 2022-12-24 01:44
![Screenshot_1](https://user-images.githubusercontent.com/111536816/209417161-1e371761-881a-49c4-bb51-da82f109b56a.png)

**Comment by Mozoloa** [comment] 2022-12-24 13:03
That's some good info ! Maybe my function doesn't put the right quote marks around the string, hence why this could break with spaces. I don't really know how to fix this tho, I'll look into it

**Comment by bouiboui** [comment] 2022-12-25 07:10
> 1. Launch via webui-user.bat, if it works then it's odd, else:
It works for me as well!
I will take a look at what you suggested.

**Comment by bouiboui** [comment] 2022-12-25 09:13
This solves it for me (thanks ChatGPT):
```sh
function Search-RegForPyPath {
    # Try to retrieve the value of the ExecutablePath key from the HKCU hive
    $pyCore = Get-ItemProperty -Path "HKCU:\Software\Python\PythonCore\3.10" -Name ExecutablePath -ErrorAction SilentlyContinue

    # If the key was found in the HKCU hive, return the value
    if ($pyCore) {
        return $pyCore.ExecutablePath
    }

    # If the key was not found in the HKCU hive, try to retrieve it from the HKLM hive
    $pyCore = Get-ItemProperty -Path "HKLM:\Software\Python\PythonCore\3.10" -Name ExecutablePath -ErrorAction SilentlyContinue

    # If the key was found in the HKLM hive, return the value
    if ($pyCore) {
        return $pyCore.ExecutablePath
    }

    # If the key was not found in either hive, return an empty string
    return ""
}
```

At first it thought it was because `Get-ItemProperty` `-Path` was written as `-path` but that alone did not fix it.
I can do a PR if you want but that won't be before a long time.

**Comment by Mozoloa** [comment] 2022-12-25 11:35
I'm not sure this would work for OP since he has a correct python ExecutablePath in HKCU. Also my installer normally installs it for the current user only. Maybe it's the installation that's broken sometimes

**Comment by walkerakiz** [comment] 2022-12-25 12:25
> This solves it for me (thanks ChatGPT):
> 
> ```shell
> function Search-RegForPyPath {
>     # Try to retrieve the value of the ExecutablePath key from the HKCU hive
>     $pyCore = Get-ItemProperty -Path "HKCU:\Software\Python\PythonCore\3.10" -Name ExecutablePath -ErrorAction SilentlyContinue
> 
>     # If the key was found in the HKCU hive, return the value
>     if ($pyCore) {
>         return $pyCore.ExecutablePath
>     }
> 
>     # If the key was not found in the HKCU hive, try to retrieve it from the HKLM hive
>     $pyCore = Get-ItemProperty -Path "HKLM:\Software\Python\PythonCore\3.10" -Name ExecutablePath -ErrorAction SilentlyContinue
> 
>     # If the key was found in the HKLM hive, return the value
>     if ($pyCore) {
>         return $pyCore.ExecutablePath
>     }
> 
>     # If the key was not found in either hive, return an empty string
>     return ""
> }
> ```
> 
> At first it thought it was because `Get-ItemProperty` `-Path` was written as `-path` but that alone did not fix it. I can do a PR if you want but that won't be before a long time.

Woot! That worked for me aswell, now launcher works! :D

**Comment by Mozoloa** [comment] 2022-12-25 12:44
Haha okay you guys i'll refactor the code and push it to see how that goes

**Comment by walkerakiz** [comment] 2022-12-25 12:55
So I tried to see via chatGTP to see how it did, those are the chatgtp explanations:

Here are the changes that I made:

1. I replaced logger.info and logger.warn with Write-Host, which is a PowerShell cmdlet used to output messages to the console.
2. I added -ForegroundColor parameter to Write-Host to specify the color of the output text.
3. I replaced "n"with the escape sequence"n", which is used to add a newline in PowerShell.

**Comment by Mozoloa** [comment] 2022-12-25 13:04
> So I tried to see via chatGTP to see how it did, those are the chatgtp explanations:
> 
> Here are the changes that I made:
> 
> 1. I replaced **logger.info** and **logger.warn** with **Write-Host**, which is a PowerShell cmdlet used to output messages to the console.
> 2. I added **-ForegroundColor** parameter to **Write-Host** to specify the color of the output text.
> 3. I replaced "n"**with the escape sequence**"n", which is used to add a newline in PowerShell.

My custom "logger.xxx" function already is a write-host with different colours, you just hardcoded something that was already abstracted.

Other than that, **this fix doesn't actually work** as the `Get-ItemProperty` commands are broken, there will never be a "ExecutablePath" in the 3.10 key, it's in the installPath subkey.

What basically ends up happening is the two If statements are always false and it just returns an empty string, which is the same as entirely bypassing the function or launching webui-user.bat with nothing in the "PYTHON=" field, which should default to the system python path, and would prevent the UI from launching if someone had previously installed another incompatible Python version

**Comment by Mozoloa** [comment] 2022-12-26 21:07
So some user on discord has managed to get past this by just reinstalling, it turns out python had not been installed the first time, could you try this ?

**Comment by walkerakiz** [comment] 2022-12-26 23:31
> So some user on discord has managed to get past this by just reinstalling, it turns out python had not been installed the first time, could you try this ?

Before that fix I did by the one up, I really did reinstalled and clean install again like 6-7 times? Don't want to do it again 😅

**Comment by Mozoloa** [comment] 2022-12-27 10:03
As I've said that's not a fix, you've just removed an important check. Try to install python via https://www.python.org/ftp/python/3.10.8/python-3.10.8-amd64.exe
and check _add to path_ in the first screen, see if it works (and reverse your fix), tell me if it still glitches out

**Comment by walkerakiz** [comment] 2022-12-27 14:05
> As I've said that's not a fix, you've just removed an important check. Try to install python via https://www.python.org/ftp/python/3.10.8/python-3.10.8-amd64.exe and check _add to path_ in the first screen, see if it works (and reverse your fix), tell me if it still glitches out

Sigh I shouldn't try to reinstall it today did what you said... deleted everything started from the zero and new issue now and can't work anymore.

"venv "D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\Scripts\Python.exe"
No Python at '"D:\Python 10\python.exe'
Press any key to continue . . ." 
And yes I've clicked add to path and checked into system environment if the path is there and yes it is and there is no other python anywhere. Tried again to reinstall it but nothing.. wont work even with  webuiuser.bat

**Comment by Mozoloa** [comment] 2022-12-27 14:11
Did you do a clean install ? If not try deleting venv

**Comment by walkerakiz** [comment] 2022-12-27 14:15
> Did you do a clean install ? If not try deleting venv

Did that aswell.. going like crazy atm.

**Comment by Mozoloa** [comment] 2022-12-27 14:19
is there really a python.exe in d:/python 10 ?

**Comment by walkerakiz** [comment] 2022-12-27 14:21
> is there really a python.exe in d:/python 10 ?

![Uploading Screenshot_1.png…]()

**Comment by walkerakiz** [comment] 2022-12-27 14:21
![Screenshot_1](https://user-images.githubusercontent.com/111536816/209679843-5550b54c-779c-4b76-933f-8efb3c35e8f4.png)
![Screenshot_2](https://user-images.githubusercontent.com/111536816/209679847-09756672-4219-442e-a695-229b123732d3.png)

**Comment by Mozoloa** [comment] 2022-12-27 14:23
The webui cmd was saying "No Python at '"D:\Python 10\python.exe'" that's why I was asking, that's not the folder you're showing here

**Comment by walkerakiz** [comment] 2022-12-27 14:25
D:\Python\Python310 thats where is my python

**Comment by Mozoloa** [comment] 2022-12-27 14:28
for some reason the webui is searching in the old folder, I'm not sure how clean your install was, I would probably try another clean install without git and python

**Comment by walkerakiz** [comment] 2022-12-27 14:29
I am giving up. Gonna stick with the normal Stable Diffusion which for some reason works.

**Comment by Mozoloa** [comment] 2022-12-27 14:32
What's do you mean the normal stable diffusion ?

**Comment by walkerakiz** [comment] 2022-12-27 14:33
Tried one more time to reinstall python and its back again the first and webuser.bat works now.Wtf is going on ^^

![Screenshot_3](https://user-images.githubusercontent.com/111536816/209681257-29970bb8-328d-47e6-90a6-c68aba90cf7e.png)

**Comment by walkerakiz** [comment] 2022-12-27 14:37
So python is fixed now, but still keep going with that glitch so I guess gotta stick with the webui-user.bat

**Comment by Mozoloa** [comment] 2022-12-27 14:39
looks like python got reinstalled in d:/python 10, the problem is with the space in the path, I'll try to force quote marks in the next update and see how that goes

**Comment by Mozoloa** [comment] 2022-12-27 14:41
Actually I have an idea, try this:
In LaunchWebUI.ps1, try to replace the python line with `$env:PYTHON = "$(Search-RegForPyPath)"`

**Comment by walkerakiz** [comment] 2022-12-27 14:43
> 

Hmm still the same issue.
Couldn't launch python

exit code: 9009

stderr:
'D:\Python' is not recognized as an internal or external command,
operable program or batch file.

Launch unsuccessful. Exiting.

**Comment by Mozoloa** [comment] 2022-12-27 14:44
what does `Get-ItemProperty -path "hkcu:\Software\Python\PythonCore\3.10\InstallPath"` give now in powershell ?

**Comment by walkerakiz** [comment] 2022-12-27 14:46
![Screenshot_4](https://user-images.githubusercontent.com/111536816/209682678-8a2f8f71-771c-4d63-a4b8-923a2c301c64.png)

**Comment by Mozoloa** [comment] 2022-12-27 14:49
Okay I have an idea, in webui-user.bat, after python write "D:\Python 10\python.exe" with the quotemarks, tell me if it works, if not, try with single quotes instead, and if it still doesn't work the problem is with the webui's programming

**Comment by walkerakiz** [comment] 2022-12-27 14:53
> Okay I have an idea, in webui-user.bat, after python write "D:\Python 10\python.exe" with the quotemarks, tell me if it works, if not, try with single quotes instead, and if it still doesn't work the problem is with the webui's programming

I added that in webui-user.bat and oepning it via the .bat either with this one command either not it works! But launcher still not works :/

**Comment by Mozoloa** [comment] 2022-12-27 15:03
So you mean it's working with "D:\Python 10\python.exe" after PYTHON=? In that cas it's my function that's broken,

Try putting this in LaunchWebUI.ps1 `$env:PYTHON = "'$(Search-RegForPyPath)'"`, there's a chance this will work

**Comment by walkerakiz** [comment] 2022-12-27 15:06
And thought it would work.. now the code error changed :D 
![Screenshot_5](https://user-images.githubusercontent.com/111536816/209685094-24e4dca6-546e-48e6-91d9-8951c01f1a2f.png)

**Comment by Mozoloa** [comment] 2022-12-27 15:30
Haha yeah it's progress, I'm on it

**Comment by Mozoloa** [comment] 2022-12-27 15:36
Try with `$env:PYTHON = ""$(Search-RegForPyPath)""`
And show me what LaunchWebUI looks like to make sure you're replacing the right thing

**Comment by walkerakiz** [comment] 2022-12-27 15:40
![Screenshot_1](https://user-images.githubusercontent.com/111536816/209688913-623b489b-0844-47ff-855a-461ff0e233c1.png)

not working , this way when i launch it wont even open the cmd when I click Launch

**Comment by Mozoloa** [comment] 2022-12-27 15:41
have you restarted the launcher every time you modified it ?

**Comment by walkerakiz** [comment] 2022-12-27 15:42
> have you restarted the launcher every time you modified it ?

Of course :D and always triple checking before writing you back

**Comment by Mozoloa** [comment] 2022-12-27 15:45
Try this, don't forget the first line
`$pyPath = Search-RegForPyPath
$env:GIT = ""
$env:PYTHON = "`"$pyPath`""
$env:VENV_DIR = ""
$env:COMMANDLINE_ARGS = "--autolaunch " + $arguments`

**Comment by Mozoloa** [comment] 2022-12-27 15:47
Try this, don't forget the first new line
```$pyPath = Search-RegForPyPath
$env:GIT = ""
$env:PYTHON = "`"$pyPath`""
$env:VENV_DIR = ""
$env:COMMANDLINE_ARGS = "--autolaunch " + $arguments```

**Comment by walkerakiz** [comment] 2022-12-27 16:45
Woot that worked!

**Comment by Mozoloa** [comment] 2022-12-27 16:47
Dope, I hope this is not a false positive again, i'll try at home

**Comment by Mozoloa** [comment] 2022-12-27 16:56
https://github.com/EmpireMediaScience/A1111-Web-UI-Installer/releases/tag/V1.3.4 pushed the fix in this release

**Closed by Mozoloa** 2022-12-27 16:56 UTC
